### ISSUE TITLE
Validation of performance

### ISSUE THREAD

**Issue by Lejboelle** [xufeifeiWHU/Mobilenet-v2-on-Movidius-stick#2]
Hi,

Great work on the translation - have you done any validation on the performance compared to the original work?

Thanks.

**Comment by xufeifeiWHU** [comment]
Hello,
I have test it seriously,
As I have mentioned in Movidius forum,
Mobilenetv2 works poor in NCS stick compared with MobileNetV1,
More precise data is : 
MobileNet v1 performs 38ms per inferencing
MobileNet v2 performs 49ms per inferencing

**Comment by xufeifeiWHU** [comment]
@Lejboelle

**Comment by Lejboelle** [comment]
Thanks, I'll have a look on the forum as well.
